In [1]:
pip -q install autogluon

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.5/259.5 kB 14.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.6/227.6 kB 18.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.1/452.1 kB 22.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 28.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.8/244.8 kB 21.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.7/72.7 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.4/287.4 kB 20.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.0/281.0 kB 22.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 38.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 827.9/827.9 kB 53.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.5/410.5 kB 29.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 504.9/504.9 kB 35.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.9/125.9 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.3/72.3 MB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 353.3/353.3 kB 27.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 89.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 742.6 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 88.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 45.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 792.2 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 46.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.3/322.3 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 18.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.7/124.7 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 963.5/963.5 kB 42.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 98.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 95.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 87.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.2/102.2 kB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.9/131.9 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 85.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 106.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.3/201.3 kB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 29.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.3/857.3 kB 50.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 kB 33.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 75.7 MB/s eta 0:00:00
  Building wheel for nvidia-ml-py3 (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.10.0+cpu requires torch==2.10.0, but you have torch 2.9.1 which is incompatible.
rasterio 1.5.0 requires click!=8.2.*,>=4.0, but you have click 8.2.1 which is incompatible.

In [2]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [3]:
import pandas as pd

# start

In [4]:
train_data = pd.read_csv("/content/train.csv")

In [5]:
train_data['History of HeartDisease or Attack'].value_counts()

History of HeartDisease or Attack
No     203322
Yes     18068
Name: count, dtype: int64

# preprocess

In [6]:
# delete target null
print(len(train_data))
train_data = train_data.dropna(subset=['History of HeartDisease or Attack'])
print(len(train_data))

223084
221390

In [7]:
train_data["Age"].describe()

count    221390.000000
mean         54.660215
std          17.773171
min          18.000000
25%          42.000000
50%          56.000000
75%          67.000000
max         100.000000
Name: Age, dtype: float64

In [8]:
import numpy as np
import pandas as pd

def create_new_features(train_data):
    # """
    # This function creates 10 new features from the existing columns in train_data.
    # It assumes that many binary columns are coded as "Yes"/"No" and converts them into 1/0.
    # It also maps categorical education and income levels into numeric scores.
    # """
    # --- Helper: Convert Yes/No to binary ---
    binary_map = {"Yes": 1, "No": 0}
    binary_cols = [
        "High Blood Pressure", "Told High Cholesterol", "Cholesterol Checked",
        "Smoked 100+ Cigarettes", "Diagnosed Stroke", "Diagnosed Diabetes",
        "Leisure Physical Activity", "Heavy Alcohol Consumption",
        "Health Care Coverage", "Doctor Visit Cost Barrier",
        "Difficulty Walking", "Vegetable or Fruit Intake (1+ per Day)"
    ]

    for col in binary_cols:
        # Create a new binary column with suffix '_bin'
        if train_data[col].dtype == object:
            train_data[col + "_bin"] = train_data[col].map(binary_map)
        else:
            train_data[col + "_bin"] = train_data[col]


    # --------Feature 2 ------------
    def categorize_bmi(bmi): # GOOD
        if bmi < 18.5:
            return "Underweight"
        elif bmi < 25:
            return "Normal weight"
        elif bmi < 30:
            return "Overweight"
        else:
            return "Obese"

    train_data['BMI Category'] = train_data['Body Mass Index'].apply(categorize_bmi)

    # # Derived Feature: Obesity Risk # may be good, GOOD
    train_data['Obesity Risk'] = ((train_data['Body Mass Index'] >= 30) & (train_data['Leisure Physical Activity'] == 'No')).astype(int)

    # #Drop column
    columns_to_drop = [
        "High Blood Pressure_bin", "Told High Cholesterol_bin", "Cholesterol Checked_bin",
        "Smoked 100+ Cigarettes_bin", "Diagnosed Stroke_bin", "Diagnosed Diabetes_bin",
        "Leisure Physical Activity_bin", "Heavy Alcohol Consumption_bin",
        "Health Care Coverage_bin", "Doctor Visit Cost Barrier_bin",
        "Difficulty Walking_bin", "Vegetable or Fruit Intake (1+ per Day)_bin",
        "Leisure Physical Activity",
    ]
    train_data = train_data.drop(columns=columns_to_drop)




    return train_data

In [9]:
train_data = create_new_features(train_data)
train_data.head(3)

,ID,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Heavy Alcohol Consumption,...,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day),BMI Category,Obesity Risk
0,train_000001,No,Yes,Yes,Yes,40.68,Yes,No,No,No,...,No,Very Poor,Yes,Female,High school graduate,"$15,000 to less than $20,000",64,Yes,Obese,1
1,train_000002,No,No,No,No,24.36,Yes,No,No,No,...,Yes,Fair,No,Female,College graduate,"Less than $10,000",50,No,Normal weight,0
2,train_000003,No,Yes,Yes,Yes,27.33,No,No,No,No,...,Yes,Very Poor,Yes,Female,High school graduate,"$75,000 or more",61,Yes,Overweight,0

In [10]:
train_data.iloc[0]

ID                                                        train_000001
History of HeartDisease or Attack                                   No
High Blood Pressure                                                Yes
Told High Cholesterol                                              Yes
Cholesterol Checked                                                Yes
Body Mass Index                                                  40.68
Smoked 100+ Cigarettes                                             Yes
Diagnosed Stroke                                                    No
Diagnosed Diabetes                                                  No
Heavy Alcohol Consumption                                           No
Health Care Coverage                                               Yes
Doctor Visit Cost Barrier                                           No
General Health                                               Very Poor
Difficulty Walking                                                 Yes
Sex                                                             Female
Education Level                                   High school graduate
Income Level                              $15,000 to less than $20,000
Age                                                                 64
Vegetable or Fruit Intake (1+ per Day)                             Yes
BMI Category                                                     Obese
Obesity Risk                                                         1
Name: 0, dtype: object

In [11]:
df_yes = train_data[train_data['History of HeartDisease or Attack'] == 'Yes'].sample(n=18068, random_state=42)
df_no = train_data[train_data['History of HeartDisease or Attack'] == 'No'].sample(n=20000, random_state=42)
train_data = pd.concat([df_yes, df_no], ignore_index=True)

In [12]:
train_data.head(3)

,ID,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Heavy Alcohol Consumption,...,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day),BMI Category,Obesity Risk
0,train_183649,Yes,Yes,Yes,Yes,26.36,No,Yes,No,No,...,No,Very Poor,Yes,Female,College graduate,"$75,000 or more",47,Yes,Overweight,0
1,train_001613,Yes,Yes,Yes,Yes,26.11,Yes,Yes,Yes,No,...,No,Poor,No,Female,Some high school,"($10,000 to less than $15,000",59,Yes,Overweight,0
2,train_072658,Yes,No,Yes,Yes,26.23,No,No,No,No,...,Yes,Poor,Yes,Female,College graduate,"$75,000 or more",58,Yes,Overweight,0

In [13]:
train_data['History of HeartDisease or Attack'].value_counts()
# train_data['General Health'].isna().sum()

History of HeartDisease or Attack
No     20000
Yes    18068
Name: count, dtype: int64

# model time

In [14]:
save_path = 'best_model'
hyperparameters = {
    'GBM': [
        {'ag_args_fit': {'num_gpus': 0}},  # Train with CPU
        {'ag_args_fit': {'num_gpus': 1}}   # Train with GPU
    ],
    'CAT': [
        {'ag_args_fit': {'num_gpus': 0}},  # Train with CPU
        {'ag_args_fit': {'num_gpus': 1}}   # Train with GPU
    ],
    'XGB': [
        {'ag_args_fit': {'num_gpus': 0}},  # Train with CPU
        {'ag_args_fit': {'num_gpus': 1}}   # Train with GPU
    ],
    'RF': [
        {'ag_args_fit': {'num_gpus': 0}},  # Train with CPU
        {'ag_args_fit': {'num_gpus': 1}}   # Train with GPU
    ],

}
time_limit=600

In [15]:
predictor = TabularPredictor(label='History of HeartDisease or Attack',
                            problem_type='binary',
                            path=save_path,
                            # eval_metric='f1_macro'
                            ).fit(
                                train_data,
                                presets='best_quality',
                                hyperparameters=hyperparameters,
                                time_limit=time_limit
                            )
print("Finish!")

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Mon Feb  2 12:27:57 UTC 2026
CPU Count:          2
Pytorch Version:    2.9.1+cu128
CUDA Version:       CUDA is not available
Memory Avail:       11.01 GB / 12.67 GB (86.9%)
Disk Space Avail:   75.29 GB / 107.72 GB (69.9%)
===================================================
Presets specified: ['best_quality']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 150s of the 600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2026-04-04 11:04:37,265	INFO worker.py:2014 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
		Context path: "/content/best_model/ds_sub_fit/sub_fit_ho"
(_dystack pid=7286) Running DyStack sub-fit ...
(_dystack pid=7286) Beginning AutoGluon training ... Time limit = 126s
(_dystack pid=7286) AutoGluon will save models to "/content/best_model/ds_sub_fit/sub_fit_ho"
(_dystack pid=7286) Train Data Rows:    33838
(_dystack pid=7286) Train Data Columns: 20
(_dystack pid=7286) Label Column:       History of HeartDisease or Attack
(_dystack pid=7286) Problem Type:       binary
(_dystack pid=7286) Preprocessing data ...
(_dystack pid=7286) Selected class <--> label mapping:  class 1 = Yes, class 0 = No
(_dystack pid=7286) 	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Yes) vs negative (No) class.
(_dystack pid=7286) 	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
(_dystack pid=7286) Using Feature Generators to preprocess the data ...
(_dystack pid=7286) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=7286) 	Available Memory:                    10013.65 MB
(_dystack pid=7286) 	Train Data (Original)  Memory Usage: 30.93 MB (0.3% of available memory)
(_dystack pid=7286) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=7286) 	Stage 1 Generators:
(_dystack pid=7286) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=7286) 			Note: Converting 10 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=7286) 	Stage 2 Generators:
(_dystack pid=7286) 		Fitting FillNaFeatureGenerator...
(_dystack pid=7286) 	Stage 3 Generators:
(_dystack pid=7286) 		Fitting IdentityFeatureGenerator...
(_dystack pid=7286) 		Fitting CategoryFeatureGenerator...
(_dystack pid=7286) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=7286) 	Stage 4 Generators:
(_dystack pid=7286) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=7286) 	Stage 5 Generators:
(_dystack pid=7286) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=7286) 	Unused Original Features (Count: 1): ['ID']
(_dystack pid=7286) 		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
(_dystack pid=7286) 		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
(_dystack pid=7286) 		These features do not need to be present at inference time.
(_dystack pid=7286) 		('object', []) : 1 | ['ID']
(_dystack pid=7286) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=7286) 		('float', [])  :  1 | ['Body Mass Index']
(_dystack pid=7286) 		('int', [])    :  2 | ['Age', 'Obesity Risk']
(_dystack pid=7286) 		('object', []) : 16 | ['High Blood Pressure', 'Told High Cholesterol', 'Cholesterol Checked', 'Smoked 100+ Cigarettes', 'Diagnosed Stroke', ...]
(_dystack pid=7286) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=7286) 		('category', [])  :  7 | ['Told High Cholesterol', 'Diagnosed Diabetes', 'General Health', 'Difficulty Walking', 'Education Level', ...]
(_dystack pid=7286) 		('float', [])     :  1 | ['Body Mass Index']
(_dystack pid=7286) 		('int', [])       :  1 | ['Age']
(_dystack pid=7286) 		('int', ['bool']) : 10 | ['High Blood Pressure', 'Cholesterol Checked', 'Smoked 100+ Cigarettes', 'Diagnosed Stroke', 'Heavy Alcohol Consumption', ...]
(_dystack pid=7286) 	0.6s = Fit runtime
(_dystack pid=7286) 	19 features in original data used to generate 19 features in processed data.
(_dystack pid=7286) 	Train Data (Processed) Memory Usage: 1.07 MB (0.0% of available memory)
(_dystack pid=7286) Data preprocessing and feature engineering runtime = 0.64s ...
(_dystack pid=7286) AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
(_dystack pid=7286) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=7286) User-specified model hyperparameters to be fit:
(_dystack pid=7286) {
(_dystack pid=7286) 	'GBM': [{'ag_args_fit': {'num_gpus': 0}}, {'ag_args_fit': {'num_gpus': 1}}],
(_dystack pid=7286) 	'CAT': [{'ag_args_fit': {'num_gpus': 0}}, {'ag_args_fit': {'num_gpus': 1}}],
(_dystack pid=7286) 	'XGB': [{'ag_args_fit': {'num_gpus': 0}}, {'ag_args_fit': {'num_gpus': 1}}],
(_dystack pid=7286) 	'RF': [{'ag_args_fit': {'num_gpus': 0}}, {'ag_args_fit': {'num_gpus': 1}}],
(_dystack pid=7286) }
(_dystack pid=7286) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=7286) Fitting 8 L1 models, fit_strategy="sequential" ...
(_dystack pid=7286) Fitting model: LightGBM_BAG_L1 ... Training model for up to 83.80s of the 125.73s of remaining time.
(_dystack pid=7286) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.28%)
(_dystack pid=7286) 	0.7879	 = Validation score   (accuracy)
(_dystack pid=7286) 	37.35s	 = Training   runtime
(_dystack pid=7286) 	0.61s	 = Validation runtime
(_dystack pid=7286) Fitting model: LightGBM_2_BAG_L1 ... Training model for up to 35.72s of the 77.65s of remaining time.
(_dystack pid=7286) 	Warning: Exception caused LightGBM_2_BAG_L1 to fail during training... Skipping this model.
(_dystack pid=7286) 		Specified num_gpus per model base is more than the total: 0
(_dystack pid=7286) Detailed Traceback:
(_dystack pid=7286) Traceback (most recent call last):
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2201, in _train_and_save
(_dystack pid=7286)     model = self._train_single(**model_fit_kwargs)
(_dystack pid=7286)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2085, in _train_single
(_dystack pid=7286)     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
(_dystack pid=7286)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 1081, in fit
(_dystack pid=7286)     kwargs = self._preprocess_fit_args(**kwargs)
(_dystack pid=7286)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 706, in _preprocess_fit_args
(_dystack pid=7286)     kwargs = self._preprocess_fit_resources(**kwargs)
(_dystack pid=7286)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 969, in _preprocess_fit_resources
(_dystack pid=7286)     return self._calculate_total_resources(silent=silent, total_resources=total_resources, parallel_hpo=parallel_hpo, **kwargs)
(_dystack pid=7286)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 841, in _calculate_total_resources
(_dystack pid=7286)     user_specified_lower_level_num_gpus = self._process_user_provided_resource_requirement_to_calculate_total_resource_when_ensemble(
(_dystack pid=7286)                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 786, in _process_user_provided_resource_requirement_to_calculate_total_resource_when_ensemble
(_dystack pid=7286)     assert user_specified_model_level_resource <= system_resource, f"Specified {resource_type} per model base is more than the total: {system_resource}"
(_dystack pid=7286)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286) AssertionError: Specified num_gpus per model base is more than the total: 0
(_dystack pid=7286) Fitting model: RandomForest_BAG_L1 ... Training model for up to 35.42s of the 77.35s of remaining time.
(_dystack pid=7286) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0, mem=0.2/9.1 GB
(_dystack pid=7286) 	0.7716	 = Validation score   (accuracy)
(_dystack pid=7286) 	16.71s	 = Training   runtime
(_dystack pid=7286) 	2.59s	 = Validation runtime
(_dystack pid=7286) Fitting model: RandomForest_2_BAG_L1 ... Training model for up to 14.40s of the 56.33s of remaining time.
(_dystack pid=7286) 	Warning: Exception caused RandomForest_2_BAG_L1 to fail during training... Skipping this model.
(_dystack pid=7286) 		Specified num_gpus per model base is more than the total: 0
(_dystack pid=7286) Detailed Traceback:
(_dystack pid=7286) Traceback (most recent call last):
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2201, in _train_and_save
(_dystack pid=7286)     model = self._train_single(**model_fit_kwargs)
(_dystack pid=7286)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2085, in _train_single
(_dystack pid=7286)     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
(_dystack pid=7286)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 1081, in fit
(_dystack pid=7286)     kwargs = self._preprocess_fit_args(**kwargs)
(_dystack pid=7286)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 706, in _preprocess_fit_args
(_dystack pid=7286)     kwargs = self._preprocess_fit_resources(**kwargs)
(_dystack pid=7286)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 969, in _preprocess_fit_resources
(_dystack pid=7286)     return self._calculate_total_resources(silent=silent, total_resources=total_resources, parallel_hpo=parallel_hpo, **kwargs)
(_dystack pid=7286)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 841, in _calculate_total_resources
(_dystack pid=7286)     user_specified_lower_level_num_gpus = self._process_user_provided_resource_requirement_to_calculate_total_resource_when_ensemble(
(_dystack pid=7286)                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 786, in _process_user_provided_resource_requirement_to_calculate_total_resource_when_ensemble
(_dystack pid=7286)     assert user_specified_model_level_resource <= system_resource, f"Specified {resource_type} per model base is more than the total: {system_resource}"
(_dystack pid=7286)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286) AssertionError: Specified num_gpus per model base is more than the total: 0
(_dystack pid=7286) Fitting model: CatBoost_BAG_L1 ... Training model for up to 14.16s of the 56.09s of remaining time.
(_dystack pid=7286) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=4.23%)
(_dystack pid=7286) 	Time limit exceeded... Skipping CatBoost_BAG_L1.
(_dystack pid=7286) Fitting model: CatBoost_2_BAG_L1 ... Training model for up to 7.54s of the 49.47s of remaining time.
(_dystack pid=7286) 	Warning: Exception caused CatBoost_2_BAG_L1 to fail during training... Skipping this model.
(_dystack pid=7286) 		Specified num_gpus per model base is more than the total: 0
(_dystack pid=7286) Detailed Traceback:
(_dystack pid=7286) Traceback (most recent call last):
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2201, in _train_and_save
(_dystack pid=7286)     model = self._train_single(**model_fit_kwargs)
(_dystack pid=7286)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/tabular/trainer/abstract_trainer.py", line 2085, in _train_single
(_dystack pid=7286)     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
(_dystack pid=7286)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 1081, in fit
(_dystack pid=7286)     kwargs = self._preprocess_fit_args(**kwargs)
(_dystack pid=7286)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 706, in _preprocess_fit_args
(_dystack pid=7286)     kwargs = self._preprocess_fit_resources(**kwargs)
(_dystack pid=7286)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 969, in _preprocess_fit_resources
(_dystack pid=7286)     return self._calculate_total_resources(silent=silent, total_resources=total_resources, parallel_hpo=parallel_hpo, **kwargs)
(_dystack pid=7286)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 841, in _calculate_total_resources
(_dystack pid=7286)     user_specified_lower_level_num_gpus = self._process_user_provided_resource_requirement_to_calculate_total_resource_when_ensemble(
(_dystack pid=7286)                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286)   File "/usr/local/lib/python3.12/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 786, in _process_user_provided_resource_requirement_to_calculate_total_resource_when_ensemble
(_dystack pid=7286)     assert user_specified_model_level_resource <= system_resource, f"Specified {resource_type} per model base is more than the total: {system_resource}"
(_dystack pid=7286)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(_dystack pid=7286) AssertionError: Specified num_gpus per model base is more than the total: 0
(_dystack pid=7286) Fitting model: XGBoost_BAG_L1 ... Training model for up to 6.73s of the 48.66s of remaining time.
(_dystack pid=7286) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.26%)
(_dystack pid=7286) 	0.7832	 = Validation score   (accuracy)
(_dystack pid=7286) 	22.18s	 = Training   runtime
(_dystack pid=7286) 	0.54s	 = Validation runtime
(_dystack pid=7286) Fitting model: WeightedEnsemble_L2 ... Training model for up to 125.73s of the 21.07s of remaining time.
(_dystack pid=7286) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.1 GB
(_dystack pid=7286) 	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
(_dystack pid=7286) 	0.7879	 = Validation score   (accuracy)
(_dystack pid=7286) 	0.13s	 = Training   runtime
(_dystack pid=7286) 	0.0s	 = Validation runtime
(_dystack pid=7286) Fitting 8 L2 models, fit_strategy="sequential" ...
(_dystack pid=7286) Fitting model: LightGBM_BAG_L2 ... Training model for up to 20.93s of the 20.93s of remaining time.
(_dystack pid=7286) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.32%)
(_dystack pid=7286) 	0.7874	 = Validation score   (accuracy)
(_dystack pid=7286) 	41.52s	 = Training   runtime
(_dystack pid=7286) 	0.2s	 = Validation runtime
(_dystack pid=7286) Fitting model: WeightedEnsemble_L3 ... Training model for up to 125.73s of the -25.33s of remaining time.
(_dystack pid=7286) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.1 GB
(_dystack pid=7286) 	Ensemble Weights: {'LightGBM_BAG_L1': 1.0}
(_dystack pid=7286) 	0.7879	 = Validation score   (accuracy)
(_dystack pid=7286) 	0.24s	 = Training   runtime
(_dystack pid=7286) 	0.0s	 = Validation runtime
(_dystack pid=7286) AutoGluon training complete, total runtime = 151.97s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 6961.1 rows/s (4230 batch size)
(_dystack pid=7286) Enabling decision threshold calibration (calibrate_decision_threshold='auto', metric is valid, problem_type is 'binary')
(_dystack pid=7286) Calibrating decision threshold to optimize metric accuracy | Checking 51 thresholds...
(_dystack pid=7286) Calibrating decision threshold via fine-grained search | Checking 38 thresholds...
(_dystack pid=7286) 	Base Threshold: 0.500	| val: 0.7879
(_dystack pid=7286) 	Best Threshold: 0.500	| val: 0.7879

Finish!

# test data

In [16]:
test_data = pd.read_csv("/content/test.csv")
test_data.head()

,ID,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day)
0,test_000001,Yes,Yes,Yes,24.84,No,No,No,Yes,No,Yes,No,Good,No,Female,Some college or technical school,"$20,000 to less than $25,000",71,Yes
1,test_000002,Yes,No,Yes,29.08,Yes,No,No,No,No,Yes,No,Fair,No,Female,College graduate,"$50,000 to less than $75,000",61,No
2,test_000003,Yes,Yes,Yes,35.23,Yes,No,No,No,No,Yes,No,Fair,Yes,Female,Some college or technical school,"Less than $10,000",67,Yes
3,test_000004,No,No,Yes,24.78,Yes,No,No,No,No,Yes,No,Fair,No,Female,Some college or technical school,"$50,000 to less than $75,000",50,Yes
4,test_000005,No,No,Yes,27.57,Yes,No,No,No,No,Yes,No,Fair,No,Male,Some college or technical school,"$25,000 to less than $35,000",40,Yes

In [17]:
for i in test_data.columns:
    print(i, end=" ")
    print(test_data[i].isna().sum())

ID 0
High Blood Pressure 0
Told High Cholesterol 0
Cholesterol Checked 0
Body Mass Index 0
Smoked 100+ Cigarettes 0
Diagnosed Stroke 0
Diagnosed Diabetes 0
Leisure Physical Activity 0
Heavy Alcohol Consumption 0
Health Care Coverage 0
Doctor Visit Cost Barrier 0
General Health 0
Difficulty Walking 0
Sex 0
Education Level 0
Income Level 0
Age 0
Vegetable or Fruit Intake (1+ per Day) 0

In [18]:
# preprocess test
test_data = create_new_features(test_data)

In [19]:
# y_pred = predictor.predict(test_data)
# y_pred.head() predict_proba

# use proba
y_pred = predictor.predict_proba(test_data)
y_pred.head()

         No       Yes
0  0.562992  0.437008
1  0.629595  0.370405
2  0.345279  0.654721
3  0.794190  0.205811
4  0.768659  0.231341

In [20]:
y_pred['outcome'] = y_pred.apply(lambda row: 'Yes' if row['Yes'] > 0.505 else 'No', axis=1)
y_pred['outcome'].value_counts()

outcome
No     49878
Yes    24483
Name: count, dtype: int64

In [21]:
sample_submission = pd.read_csv("/content/sample_submission.csv")
sample_submission.head(2)

            ID History of HeartDisease or Attack
0  test_000001                                No
1  test_000002                                No

In [22]:
# sample_submission['History of HeartDisease or Attack'] = y_pred
sample_submission['History of HeartDisease or Attack'] = y_pred['outcome']
sample_submission.tail()

                ID History of HeartDisease or Attack
74356  test_074357                                No
74357  test_074358                               Yes
74358  test_074359                               Yes
74359  test_074360                               Yes
74360  test_074361                                No

In [23]:
# sample_submission.to_csv("preprocess_first__no_prepare_52_7%confident_Accuracy_train20k_20k.csv", index=False)
sample_submission.to_csv("submission.csv", index=False)

# check submission

In [24]:
subb = pd.read_csv("/content/submission.csv")
subb['History of HeartDisease or Attack'].value_counts()

History of HeartDisease or Attack
No     49878
Yes    24483
Name: count, dtype: int64