In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [ ]:
from transformers import ViTForImageClassification, Trainer, TrainingArguments, AutoImageProcessor
from PIL import Image
import torch
import pandas as pd
import os
from torch.utils.data import Dataset, random_split

In [ ]:
model_name = "google/vit-base-patch16-224"
model = ViTForImageClassification.from_pretrained(model_name, num_labels=2,ignore_mismatched_sizes=True)
feature_extractor = AutoImageProcessor.from_pretrained(model_name)

class HouseDataset(Dataset):
    def __init__(self, df, image_folder, feature_extractor):
        self.df = df
        self.image_folder = image_folder
        self.feature_extractor = feature_extractor

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        image_path = os.path.join(self.image_folder, self.df.iloc[idx]["image_name"])
        image = Image.open(image_path).convert("RGB")
        inputs = self.feature_extractor(images=image, return_tensors="pt")
        label = torch.tensor(self.df.iloc[idx]["class"], dtype=torch.long)
        return {"pixel_values": inputs["pixel_values"].squeeze(), "labels": label}

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/super-ai-engineer-season-6-individual-hackathon-house-recognition/train.csv")
image_folder = "/content/drive/MyDrive/super-ai-engineer-season-6-individual-hackathon-house-recognition/train/train" # Corrected path
dataset = HouseDataset(df, image_folder, feature_extractor)

In [ ]:
dataset

In [ ]:
train_size = int(0.8 * len(dataset))
eval_size = len(dataset) - train_size
train_dataset, eval_dataset = random_split(dataset, [train_size, eval_size])

In [ ]:
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=4,
    weight_decay=0.01,
    report_to="none",
)

In [ ]:
from sklearn.metrics import accuracy_score
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = logits.argmax(axis=1)
    acc = accuracy_score(labels, predictions)
    return {"accuracy": acc}

model.to(device) # Explicitly move model to device

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=2364, training_loss=0.09058618565703003, metrics={'train_runtime': 1613.1206, 'train_samples_per_second': 5.857, 'train_steps_per_second': 1.465, 'total_flos': 7.321443178786652e+17, 'train_loss': 0.09058618565703003, 'epoch': 4.0})

In [ ]:
output_model_dir = "./my_trained_model"
model.save_pretrained(output_model_dir)
feature_extractor.save_pretrained(output_model_dir)
print(f"Model and feature extractor saved to {output_model_dir}")

In [ ]:
import os
directory_path = '/content/drive/MyDrive/super-ai-engineer-season-6-individual-hackathon-house-recognition/train/'

if os.path.exists(directory_path):
    contents = os.listdir(directory_path)
    print(f"Contents of '{directory_path}':")
    # Display first 10 items if there are many
    if len(contents) > 10:
        for item in contents[:10]:
            print(item)
        print(f"... and {len(contents) - 10} more items.")
    else:
        for item in contents:
            print(item)
else:
    print(f"Directory not found: {directory_path}")

Contents of '/content/drive/MyDrive/super-ai-engineer-season-6-individual-hackathon-house-recognition/train/':
train

In [ ]:
def predict(images_folder, model, feature_extractor, device):
    model.eval()
    predictions = []
    image_files = [f for f in os.listdir(images_folder) if f.endswith(".jpg") or f.endswith(".png")]

    for image_file in image_files:
        image_path = os.path.join(images_folder, image_file)
        image = Image.open(image_path).convert("RGB")
        inputs = feature_extractor(images=image, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model(**inputs)
            predicted_label = torch.argmax(outputs.logits, dim=-1).item()
        predictions.append((image_file, predicted_label))

    return predictions

In [ ]:
test_folder = "/content/drive/MyDrive/super-ai-engineer-season-6-individual-hackathon-house-recognition/test/test"
predictions = predict(test_folder, model, feature_extractor,device)

In [ ]:
predictions

[('5b22e513.jpg', 1),
 ('7e78ba7d.jpg', 1),
 ('7045ee0e.jpg', 1),
 ('583e01c9.jpg', 0),
 ('5bcca9b9.jpg', 1),
 ('5c421eed.jpg', 1),
 ('69e54e88.jpg', 0),
 ('8176d497.jpg', 1),
 ('6cf50ba4.jpg', 1),
 ('5aca8314.jpg', 1),
 ('72ce7f51.jpg', 1),
 ('5c43fc0d.jpg', 0),
 ('6d626e6c.jpg', 0),
 ('6976bdce.jpg', 0),
 ('77770040.jpg', 0),
 ('60aefb64.jpg', 0),
 ('67d766d2.jpg', 1),
 ('655d8bff.jpg', 0),
 ('673b02ea.jpg', 0),
 ('7a101d27.jpg', 0),
 ('832900d5.jpg', 0),
 ('711bde86.jpg', 0),
 ('645e314f.jpg', 0),
 ('7b5e37f5.jpg', 1),
 ('7e8862e8.jpg', 0),
 ('71dd0a48.jpg', 1),
 ('78fb392a.jpg', 1),
 ('81bc175f.jpg', 0),
 ('806357e2.jpg', 1),
 ('7d7a3d8c.jpg', 0),
 ('754a112d.jpg', 1),
 ('791982df.jpg', 0),
 ('74d21a05.jpg', 1),
 ('7b304617.jpg', 0),
 ('5f7a930c.jpg', 1),
 ('62784888.jpg', 1),
 ('582c787c.jpg', 0),
 ('5f033aaf.jpg', 1),
 ('7c112068.jpg', 0),
 ('5e8aea48.jpg', 0),
 ('6e0cabd5.jpg', 1),
 ('7ee9ab15.jpg', 0),
 ('83f20d72.jpg', 0),
 ('71032a54.jpg', 0),
 ('75babc9b.jpg', 1),
 ('73729abb.jpg', 0),
 ('6e609a75.jpg', 1),
 ('83dd9020.jpg', 1),
 ('6ee716ef.jpg', 0),
 ('683d8605.jpg', 0),
 ('7a57fa54.jpg', 0),
 ('7c5d7eb9.jpg', 1),
 ('6d3cad6b.jpg', 0),
 ('80cec1c9.jpg', 1),
 ('5994b592.jpg', 0),
 ('6a879f71.jpg', 0),
 ('78922849.jpg', 0),
 ('78a9996e.jpg', 1),
 ('83235a6b.jpg', 0),
 ('6a4a2b23.jpg', 0),
 ('6816f4bc.jpg', 1),
 ('7a44c39b.jpg', 1),
 ('656e8851.jpg', 1),
 ('81fb9fd7.jpg', 1),
 ('5f5ef892.jpg', 0),
 ('7a211113.jpg', 0),
 ('65a07b78.jpg', 0),
 ('7990af53.jpg', 1),
 ('814b66b1.jpg', 1),
 ('73bd7d72.jpg', 1),
 ('64bb2834.jpg', 0),
 ('67e60873.jpg', 1),
 ('741a02b2.jpg', 1),
 ('6344534a.jpg', 0),
 ('6ebe19dd.jpg', 1),
 ('6387d951.jpg', 1),
 ('5e2d50a4.jpg', 1),
 ('6121332d.jpg', 0),
 ('645db703.jpg', 1),
 ('5fe420e8.jpg', 1),
 ('7a920b80.jpg', 0),
 ('79e5e450.jpg', 0),
 ('7f6c2638.jpg', 0),
 ('6b457536.jpg', 1),
 ('6b771322.jpg', 1),
 ('76d68031.jpg', 0),
 ('72454909.jpg', 0),
 ('602e6224.jpg', 0),
 ('68156078.jpg', 0),
 ('62187266.jpg', 1),
 ('6f62887b.jpg', 1),
 ('69c0ed63.jpg', 1),
 ('7ea36d0f.jpg', 0),
 ('79146832.jpg', 0),
 ('774f33a8.jpg', 0),
 ('650d6e59.jpg', 1),
 ('63ce4369.jpg', 0),
 ('74ce4676.jpg', 0),
 ('76bae481.jpg', 0),
 ('7d5c1720.jpg', 0),
 ('6aebd62e.jpg', 1),
 ('64a29118.jpg', 1),
 ('713e4b53.jpg', 1),
 ('5e0166f8.jpg', 1),
 ('7ca0a84e.jpg', 0),
 ('7f90ee2c.jpg', 0),
 ('67d3ccdf.jpg', 1),
 ('607b0dfe.jpg', 1),
 ('7ea2fb36.jpg', 1),
 ('5d2293a9.jpg', 0),
 ('81f26568.jpg', 0),
 ('593f5feb.jpg', 1),
 ('839ae712.jpg', 1),
 ('7d61cbdb.jpg', 0),
 ('767b278e.jpg', 1),
 ('61bac937.jpg', 0),
 ('6d5721a1.jpg', 1),
 ('7e2030a0.jpg', 1),
 ('77cae88f.jpg', 1),
 ('7787dbaa.jpg', 1),
 ('650f6075.jpg', 0),
 ('844130ad.jpg', 0),
 ('7202a063.jpg', 0),
 ('83fa81e2.jpg', 0),
 ('77dcca0c.jpg', 1),
 ('699296dc.jpg', 0),
 ('72c83667.jpg', 0),
 ('7cedad8c.jpg', 1),
 ('6a3448d9.jpg', 0),
 ('5cf0912c.jpg', 0),
 ('632726ba.jpg', 1),
 ('65301437.jpg', 1),
 ('75fe04de.jpg', 0),
 ('825b04fe.jpg', 0),
 ('5ea84627.jpg', 1),
 ('5c59c118.jpg', 0),
 ('6608aa80.jpg', 1),
 ('7db761d4.jpg', 0),
 ('63b4fe02.jpg', 1),
 ('61754b7d.jpg', 1),
 ('70a0cf01.jpg', 0),
 ('725cb133.jpg', 0),
 ('630ca612.jpg', 1),
 ('7e6cafaa.jpg', 1),
 ('78c097a0.jpg', 1),
 ('656fc174.jpg', 0),
 ('5913e805.jpg', 1),
 ('63d13ecb.jpg', 0),
 ('6e32a8c0.jpg', 0),
 ('7ff8da4e.jpg', 0),
 ('7bb02ebb.jpg', 0),
 ('74750a38.jpg', 1),
 ('75e18fe0.jpg', 1),
 ('73af8711.jpg', 1),
 ('67e39825.jpg', 0),
 ('5af5198a.jpg', 0),
 ('7ce8fc51.jpg', 0),
 ('6feb260e.jpg', 0),
 ('7eeee8e1.jpg', 0),
 ('7e092106.jpg', 0),
 ('724b5ead.jpg', 0),
 ('6535e588.jpg', 1),
 ('6bc4b3e7.jpg', 0),
 ('597df2f7.jpg', 0),
 ('6301b5ad.jpg', 1),
 ('82da3ef8.jpg', 1),
 ('715a666a.jpg', 1),
 ('7fdc9698.jpg', 0),
 ('64bb87d7.jpg', 1),
 ('6cb6f1a0.jpg', 0),
 ('5fb482dc.jpg', 1),
 ('60bb9abd.jpg', 1),
 ('80e71a89.jpg', 0),
 ('7ba62bd4.jpg', 0),
 ('7bd7b92f.jpg', 0),
 ('735dfd16.jpg', 1),
 ('6f01272a.jpg', 1),
 ('7a45401e.jpg', 0),
 ('7aad369d.jpg', 1),
 ('7fd6caef.jpg', 1),
 ('635b361b.jpg', 0),
 ('5f7d69e3.jpg', 1),
 ('67bd97de.jpg', 0),
 ('5d6952ac.jpg', 0),
 ('64db070d.jpg', 0),
 ('6873f22d.jpg', 1),
 ('6ba3e83e.jpg', 1),
 ('7c675383.jpg', 0),
 ('73ab6cfc.jpg', 0),
 ('5ad77b0a.jpg', 0),
 ('78c3bb06.jpg', 0),
 ('6189c8fa.jpg', 1),
 ('828d7d35.jpg', 0),
 ('60080d3e.jpg', 1),
 ('5b7f5128.jpg', 1),
 ('5da44a16.jpg', 0),
 ('7e90f408.jpg', 1),
 ('74ad8c45.jpg', 1),
 ('781c193c.jpg', 0),
 ('82402242.jpg', 0),
 ('78821031.jpg', 1),
 ('7d72abd0.jpg', 0),
 ('6fe9e031.jpg', 0),
 ('737506e9.jpg', 0),
 ('6506717c.jpg', 0),
 ('5b9ddac2.jpg', 1),
 ('736e019f.jpg', 1),
 ('79109903.jpg', 1),
 ('58267211.jpg', 1),
 ('7dc9c0f9.jpg', 0),
 ('7d762131.jpg', 1),
 ('75311361.jpg', 0),
 ('5f229900.jpg', 0),
 ('8ce5fd60.jpg', 0),
 ('87a7ca7f.jpg', 0),
 ('a8d4d78b.jpg', 1),
 ('a9e9d863.jpg', 1),
 ('a7fe5e6e.jpg', 0),
 ('a140c4ef.jpg', 0),
 ('8b2e783f.jpg', 0),
 ('9459a905.jpg', 1),
 ('aaf94ab7.jpg', 0),
 ('b510aaf0.jpg', 1),
 ('a5d83395.jpg', 1),
 ('ab14b28a.jpg', 0),
 ('af72bace.jpg', 0),
 ('b3f0f04b.jpg', 1),
 ('93246b0d.jpg', 0),
 ('8f81b246.jpg', 0),
 ('95ee6fe9.jpg', 1),
 ('958314f5.jpg', 0),
 ('8aae7930.jpg', 1),
 ('a58ef785.jpg', 1),
 ('b0c149d4.jpg', 0),
 ('9a9f6c5e.jpg', 1),
 ('a1bb6c6f.jpg', 1),
 ('8ce30277.jpg', 1),
 ('917771ce.jpg', 0),
 ('aa9d5db0.jpg', 0),
 ('884397f5.jpg', 0),
 ('ae089c2f.jpg', 0),
 ('98bd060e.jpg', 1),
 ('9a38df21.jpg', 0),
 ('9cb7a124.jpg', 1),
 ('a0faaf76.jpg', 1),
 ('9404ac02.jpg', 1),
 ('9bfc35a3.jpg', 1),
 ('8e3ae715.jpg', 1),
 ('8db8f8be.jpg', 0),
 ('b3b9a47b.jpg', 1),
 ('90b17e73.jpg', 0),
 ('8582f6c4.jpg', 0),
 ('8bd8fa96.jpg', 1),
 ('b0b8958e.jpg', 0),
 ('b2864a5f.jpg', 0),
 ('ac02f2ab.jpg', 1),
 ('8ff9dfd9.jpg', 1),
 ('9b764ff5.jpg', 0),
 ('a55e9e83.jpg', 1),
 ('a2e57b4d.jpg', 1),
 ('89fcf431.jpg', 1),
 ('959b3b84.jpg', 0),
 ('8623c63c.jpg', 1),
 ('9d167923.jpg', 0),
 ('8fce61a5.jpg', 1),
 ('b04e2a06.jpg', 0),
 ('a32d2442.jpg', 0),
 ('93e4715c.jpg', 0),
 ('a86bd98b.jpg', 0),
 ('9696d4b0.jpg', 1),
 ('899293d5.jpg', 1),
 ('92fdff7f.jpg', 1),
 ('9a658a4b.jpg', 0),
 ('8b24d4fe.jpg', 0),
 ('aea50419.jpg', 1),
 ('a5c3e10d.jpg', 0),
 ('a971f9db.jpg', 1),
 ('8adc0dc1.jpg', 1),
 ('9a99e2e3.jpg', 1),
 ('96a3962a.jpg', 0),
 ('a49061cd.jpg', 1),
 ('9ab47f11.jpg', 0),
 ('97946f3d.jpg', 1),
 ('8ef5370d.jpg', 0),
 ('8a60480c.jpg', 0),
 ('a0d1d53a.jpg', 0),
 ('ae174749.jpg', 1),
 ('8ec0e07d.jpg', 0),
 ('a27243d6.jpg', 1),
 ('aaea811c.jpg', 0),
 ('96601579.jpg', 0),
 ('9e4334b4.jpg', 0),
 ('92d1bc81.jpg', 1),
 ('a31ca645.jpg', 0),
 ('b0428960.jpg', 1),
 ('897e6108.jpg', 1),
 ('8e8467e9.jpg', 0),
 ('8ba702ed.jpg', 1),
 ('aa0e011b.jpg', 1),
 ('9dce64a6.jpg', 1),
 ('887f5c9f.jpg', 0),
 ('a5261896.jpg', 0),
 ('8e999410.jpg', 0),
 ('8dc1516a.jpg', 0),
 ('9fa1ecd6.jpg', 1),
 ('9635f696.jpg', 1),
 ('a38718f4.jpg', 1),
 ('af5cdbe2.jpg', 1),
 ('8917f559.jpg', 0),
 ('a7eb55a2.jpg', 0),
 ('9d2d06c1.jpg', 0),
 ('93c29594.jpg', 0),
 ('b1c66306.jpg', 0),
 ('ab1e40b9.jpg', 0),
 ('9909c6b0.jpg', 1),
 ('b002487d.jpg', 0),
 ('b1c67ce9.jpg', 1),
 ('90371f9a.jpg', 1),
 ('ae71ea5b.jpg', 0),
 ('9435a1e5.jpg', 1),
 ('9c4f6921.jpg', 1),
 ('acd08c44.jpg', 0),
 ('9b8b6867.jpg', 0),
 ('9a918ce3.jpg', 0),
 ('b17c8bfe.jpg', 0),
 ('8ed6a7b5.jpg', 1),
 ('9a3e6aff.jpg', 0),
 ('9084e219.jpg', 1),
 ('a7398164.jpg', 1),
 ('8a284c5c.jpg', 1),
 ('b0c973c3.jpg', 1),
 ('88bb2b03.jpg', 0),
 ('84bb5ead.jpg', 1),
 ('abfa2a8f.jpg', 0),
 ('9cac80e7.jpg', 1),
 ('9c45ddb2.jpg', 1),
 ('a3bf7654.jpg', 0),
 ('8cd4979e.jpg', 0),
 ('89b0d845.jpg', 1),
 ('931726eb.jpg', 0),
 ('9a51258c.jpg', 0),
 ('9f72698b.jpg', 1),
 ('adb7e97b.jpg', 1),
 ('a51d7182.jpg', 0),
 ('922504b9.jpg', 1),
 ('9c05fea1.jpg', 0),
 ('9736ac21.jpg', 1),
 ('8d3c183a.jpg', 1),
 ('a60d6c41.jpg', 0),
 ('9e1de42c.jpg', 0),
 ('87c285bc.jpg', 0),
 ('9db2bde8.jpg', 1),
 ('a65eebe3.jpg', 0),
 ('87d9797d.jpg', 1),
 ('9ad71267.jpg', 1),
 ('a799221f.jpg', 1),
 ('ad987cbe.jpg', 1),
 ('90f03941.jpg', 1),
 ('97020557.jpg', 0),
 ('aea73d4c.jpg', 1),
 ('ad6a7967.jpg', 1),
 ('8adf335a.jpg', 1),
 ('a58bd0db.jpg', 1),
 ('b1b16817.jpg', 0),
 ('af1d2c47.jpg', 1),
 ('86b199ef.jpg', 0),
 ('a3859909.jpg', 1),
 ('a660e78e.jpg', 1),
 ('98768d3f.jpg', 1),
 ('924a6a89.jpg', 1),
 ('a1b86d28.jpg', 1),
 ('8d1a2abc.jpg', 0),
 ('8abeb5d0.jpg', 0),
 ('aaa91779.jpg', 1),
 ('8c31d467.jpg', 0),
 ('a453349b.jpg', 1),
 ('acce0323.jpg', 0),
 ('9f266a65.jpg', 1),
 ('8ddd81b8.jpg', 0),
 ('93d9e78b.jpg', 1),
 ('8cc2d29c.jpg', 1),
 ('b09ecc46.jpg', 0),
 ('ab1d372e.jpg', 1),
 ('906ff37c.jpg', 1),
 ('914e0e23.jpg', 1),
 ('9b172082.jpg', 1),
 ('9d779855.jpg', 1),
 ('96e72d26.jpg', 0),
 ('af3c50f6.jpg', 0),
 ('9d0c4473.jpg', 1),
 ('9fa6c971.jpg', 1),
 ('8c968c1c.jpg', 0),
 ('b0cfa983.jpg', 1),
 ('8eab133b.jpg', 0),
 ('9d30bc51.jpg', 1),
 ('a352d477.jpg', 0),
 ('88a97bbd.jpg', 1),
 ('b0c5d90a.jpg', 1),
 ('adacf01e.jpg', 0),
 ('a1873278.jpg', 1),
 ('973c3887.jpg', 0),
 ('954d962f.jpg', 1),
 ('a232de2f.jpg', 0),
 ('9dec333f.jpg', 0),
 ('b079fd05.jpg', 1),
 ('aa1631d7.jpg', 0),
 ('a7402128.jpg', 0),
 ('8e379a63.jpg', 1),
 ('9a74f200.jpg', 1),
 ('a0301211.jpg', 1),
 ('a54ba1a5.jpg', 0),
 ('985ef8e8.jpg', 1),
 ('8470632a.jpg', 0),
 ('b14a2f05.jpg', 1),
 ('8b06b40f.jpg', 0),
 ('a255ac7f.jpg', 0),
 ('8a218a02.jpg', 0),
 ('9efd3e9d.jpg', 1),
 ('a8261e6a.jpg', 0),
 ('b233ede2.jpg', 0),
 ('a9fbdd28.jpg', 1),
 ('a3f61e9f.jpg', 1),
 ('87615100.jpg', 0),
 ('9d90310f.jpg', 1),
 ('9214ae8f.jpg', 0),
 ('96e0e062.jpg', 1),
 ('84b06786.jpg', 0),
 ('8bcfc0d2.jpg', 0),
 ('a8d6a155.jpg', 0),
 ('b1027137.jpg', 1),
 ('96e84245.jpg', 1),
 ('8d9eaa59.jpg', 0),
 ('98873a6d.jpg', 0),
 ('970e7250.jpg', 0),
 ('9faef6d1.jpg', 1),
 ('a2067109.jpg', 1),
 ('b17ced93.jpg', 0),
 ('9de1dc40.jpg', 1),
 ('8b8ec6b7.jpg', 1),
 ('a5df00e4.jpg', 0),
 ('a50c7f58.jpg', 1),
 ('9a7df9ec.jpg', 0),
 ('9e836a3c.jpg', 1),
 ('b21aaede.jpg', 0),
 ('98bc7669.jpg', 1),
 ('89d47be9.jpg', 0),
 ('8f23d547.jpg', 0),
 ('9f6d8757.jpg', 0),
 ('94cdd6da.jpg', 0),
 ('9e7b98ed.jpg', 0),
 ('89216483.jpg', 0),
 ('a0178506.jpg', 0),
 ('b26f3fa8.jpg', 1),
 ('9d9b2036.jpg', 1),
 ('90ea2194.jpg', 1),
 ('97e3d015.jpg', 1),
 ('8e40c4be.jpg', 0),
 ('a3b49613.jpg', 0),
 ('b3df6371.jpg', 1),
 ('a359c9de.jpg', 0),
 ('a944fbf8.jpg', 1),
 ('848fa28e.jpg', 1),
 ('969e4be8.jpg', 0),
 ('a34abea0.jpg', 0),
 ('86175aa8.jpg', 0),
 ('9383fc3f.jpg', 1),
 ('a8dbcd52.jpg', 0),
 ('9f253045.jpg', 0),
 ('94c28072.jpg', 0),
 ('8edefb90.jpg', 1),
 ('8df7aec6.jpg', 1),
 ('91a9eca6.jpg', 0),
 ('91ea5755.jpg', 0),
 ('af393f0c.jpg', 1),
 ('902e63d2.jpg', 0),
 ('9f8950de.jpg', 0),
 ('880dfb48.jpg', 0),
 ('9accf8a6.jpg', 0),
 ('9341c391.jpg', 1),
 ('99fab84f.jpg', 0),
 ('9ea71b8b.jpg', 1),
 ('8779fdb4.jpg', 0),
 ('87f0034a.jpg', 0),
 ('ac13f8aa.jpg', 0),
 ('90b65aa6.jpg', 0),
 ('afeb1f4a.jpg', 0),
 ('92caac42.jpg', 0),
 ('ab45730f.jpg', 0),
 ('96499ddf.jpg', 0),
 ('98df3c66.jpg', 1),
 ('8634cb83.jpg', 0),
 ('84988add.jpg', 1),
 ('9cc414e3.jpg', 1),
 ('85e6ac9a.jpg', 1),
 ('8ab3d898.jpg', 0),
 ('8602a8d7.jpg', 0),
 ('95fc1f77.jpg', 1),
 ('ae53a6a5.jpg', 1),
 ('9b25615e.jpg', 0),
 ('afab7a60.jpg', 0),
 ('8b1ce347.jpg', 0),
 ('9ee9161f.jpg', 1),
 ('a6154645.jpg', 0),
 ('9f60d126.jpg', 0),
 ('9be0a6f9.jpg', 0),
 ('9b87ba4e.jpg', 1),
 ('a96918d4.jpg', 0),
 ('a3c844f1.jpg', 0),
 ('a3a5b050.jpg', 0),
 ('acf323a5.jpg', 1),
 ('a69b32bc.jpg', 0),
 ('a956fc6f.jpg', 0),
 ('a5b8517e.jpg', 0),
 ('b1c0df24.jpg', 1),
 ('a8eca0fd.jpg', 0),
 ('9f37ecb6.jpg', 0),
 ('95fea609.jpg', 1),
 ('ab1ed995.jpg', 0),
 ('b41adb8e.jpg', 1),
 ('aa00a70f.jpg', 1),
 ('acfb394d.jpg', 1),
 ('8789fe5d.jpg', 0),
 ('acb89d9c.jpg', 0),
 ('a4418dbf.jpg', 0),
 ('9b5854ae.jpg', 1),
 ('aeee6018.jpg', 1),
 ('94f545f1.jpg', 1),
 ('98eb277a.jpg', 1),
 ('8a35d4e2.jpg', 1),
 ('93e4e51b.jpg', 0),
 ('b1aafe51.jpg', 0),
 ('afe3bb15.jpg', 1),
 ('b38a84f6.jpg', 1),
 ('b6474da2.jpg', 0),
 ('d0b790b8.jpg', 1),
 ('ca6dd7cf.jpg', 0),
 ('d0f7b2f9.jpg', 1),
 ('d4d23a5d.jpg', 1),
 ('b69f38f2.jpg', 0),
 ('e0462caa.jpg', 0),
 ('c85c039f.jpg', 1),
 ('c87b2c94.jpg', 0),
 ('cbce8726.jpg', 0),
 ('cb508be0.jpg', 1),
 ('e89ee007.jpg', 1),
 ('cc13f6f4.jpg', 1),
 ('d54b10db.jpg', 0),
 ('d3c57931.jpg', 0),
 ('d7b36593.jpg', 0),
 ('e57009e7.jpg', 1),
 ('edee4add.jpg', 1),
 ('e24420c1.jpg', 0),
 ('d9619031.jpg', 1),
 ('e16b3be5.jpg', 1),
 ('d2971830.jpg', 0),
 ('e035ad5b.jpg', 1),
 ('e85f01f4.jpg', 1),
 ('c195428b.jpg', 1),
 ('d943e0c8.jpg', 0),
 ('c33c19b1.jpg', 0),
 ('e91bb2b8.jpg', 1),
 ('e2a8da09.jpg', 0),
 ('e0370240.jpg', 1),
 ('ecc33630.jpg', 1),
 ('c358badf.jpg', 0),
 ('ea1b867d.jpg', 1),
 ('be60a90d.jpg', 0),
 ('c1284296.jpg', 0),
 ('e73d2481.jpg', 0),
 ('c6589006.jpg', 0),
 ('d4b16499.jpg', 0),
 ('e96dcb75.jpg', 0),
 ('bb13f35d.jpg', 0),
 ('d8824652.jpg', 0),
 ('d1b21893.jpg', 1),
 ('d7b45b59.jpg', 0),
 ('e16354aa.jpg', 1),
 ('c96b78f5.jpg', 1),
 ('c7d7c486.jpg', 1),
 ('bbb92d47.jpg', 0),
 ('e927a0e2.jpg', 1),
 ('ed44ac4d.jpg', 1),
 ('eb14acdb.jpg', 1),
 ('cea39bd5.jpg', 1),
 ('df12288f.jpg', 1),
 ('e1252655.jpg', 0),
 ('e8156faf.jpg', 0),
 ('de46dae2.jpg', 1),
 ('ec045077.jpg', 0),
 ('d60c17a1.jpg', 1),
 ('cb41bd82.jpg', 0),
 ('ca503ddb.jpg', 0),
 ('d77c03a3.jpg', 1),
 ('e026753e.jpg', 1),
 ('e660220c.jpg', 1),
 ('e2401aa6.jpg', 0),
 ('ba58e2a0.jpg', 0),
 ('c348b82b.jpg', 0),
 ('d1c2658f.jpg', 0),
 ('c776a31e.jpg', 0),
 ('b93b7823.jpg', 1),
 ('c336ce30.jpg', 1),
 ('c0f23990.jpg', 0),
 ('e4c2cc22.jpg', 0),
 ('e754a4df.jpg', 0),
 ('d8b5d37a.jpg', 0),
 ('d90faa29.jpg', 1),
 ('ce327b46.jpg', 0),
 ('bec1ce70.jpg', 0),
 ('de9e2b6e.jpg', 1),
 ('d884d1a7.jpg', 1),
 ('d97916a0.jpg', 1),
 ('d0647635.jpg', 1),
 ('bac653b4.jpg', 0),
 ('d9ca5d5f.jpg', 1),
 ('bb943f28.jpg', 0),
 ('c74652c2.jpg', 0),
 ('e7e40569.jpg', 1),
 ('e61c46aa.jpg', 0),
 ('d6f7f529.jpg', 0),
 ('d6207ea6.jpg', 0),
 ('e8433345.jpg', 1),
 ('b95928d0.jpg', 1),
 ('dbe7b45d.jpg', 0),
 ('dee9804e.jpg', 0),
 ('cde587dd.jpg', 1),
 ('d8d67dcf.jpg', 1),
 ('be6b83c5.jpg', 1),
 ('bab459be.jpg', 0),
 ('e9bfa151.jpg', 1),
 ('e4b420b0.jpg', 0),
 ('da357006.jpg', 1),
 ('d0e41ccf.jpg', 1),
 ('c7ad91c5.jpg', 0),
 ('c24fd556.jpg', 0),
 ('e7a6955d.jpg', 1),
 ('e585c5ef.jpg', 0),
 ('d17a09eb.jpg', 0),
 ('c2ccbdad.jpg', 1),
 ('b8c128fc.jpg', 0),
 ('c8fd841f.jpg', 1),
 ('b6d0e5d0.jpg', 0),
 ('d1e2bf36.jpg', 1),
 ('caf03c44.jpg', 1),
 ('d90dbf37.jpg', 0),
 ('dfcba56a.jpg', 1),
 ('c346950c.jpg', 1),
 ('c8448a94.jpg', 0),
 ('d54e3433.jpg', 0),
 ('dfd0876d.jpg', 0),
 ('c1f7b4f6.jpg', 1),
 ('b5a13387.jpg', 0),
 ('cee7a0b2.jpg', 1),
 ('cddbcc07.jpg', 1),
 ('df36b626.jpg', 0),
 ('e0e92023.jpg', 0),
 ('bf17d933.jpg', 0),
 ('d73c28f1.jpg', 0),
 ('c95e1a8a.jpg', 0),
 ('c4fb5b5c.jpg', 1),
 ('d9d7736c.jpg', 0),
 ('e5190015.jpg', 0),
 ('c6d98a5a.jpg', 0),
 ('da030043.jpg', 0),
 ('b70954f3.jpg', 0),
 ('eae0945a.jpg', 0),
 ('c2d3de3c.jpg', 0),
 ('e6246fb6.jpg', 0),
 ('d05f85bb.jpg', 1),
 ('d2ac9ddf.jpg', 1),
 ('e96cef2b.jpg', 1),
 ('de64afe0.jpg', 0),
 ('c4d536d5.jpg', 1),
 ('e7c48842.jpg', 1),
 ('caf9eec7.jpg', 1),
 ('c6a0e52f.jpg', 1),
 ('ce27fd73.jpg', 0),
 ('e7b16a85.jpg', 1),
 ('b8f7b417.jpg', 1),
 ('d875b6d9.jpg', 0),
 ('beb7d70b.jpg', 0),
 ('d18836ca.jpg', 1),
 ('cf90a416.jpg', 0),
 ('e217629c.jpg', 0),
 ('c37dbcf4.jpg', 0),
 ('beac498c.jpg', 0),
 ('d11bcf44.jpg', 1),
 ('c87aa242.jpg', 0),
 ('ed4a00c7.jpg', 1),
 ('d993e17a.jpg', 1),
 ('e851fb72.jpg', 0),
 ('d4a735b7.jpg', 1),
 ('bb87f203.jpg', 0),
 ('e1484aff.jpg', 0),
 ('e6fddf67.jpg', 1),
 ('d0f88734.jpg', 1),
 ('dd58859b.jpg', 0),
 ('db1725e2.jpg', 0),
 ('bc2ed46a.jpg', 1),
 ('cf65954e.jpg', 0),
 ('ca941aa3.jpg', 1),
 ('eaca09f4.jpg', 1),
 ('da5ee16b.jpg', 1),
 ('c526a97f.jpg', 1),
 ('dc648f14.jpg', 1),
 ('d30d00ed.jpg', 1),
 ('ea3d1db5.jpg', 1),
 ('e1eb277e.jpg', 0),
 ('cc826479.jpg', 0),
 ('c9d1a911.jpg', 0),
 ('dcf84e2c.jpg', 1),
 ('d8418bcc.jpg', 1),
 ('c1eb81b4.jpg', 0),
 ('ed4e0661.jpg', 0),
 ('e4267abb.jpg', 0),
 ('c3726bb5.jpg', 0),
 ('d7afe91d.jpg', 1),
 ('d664aa29.jpg', 0),
 ('d5fc6628.jpg', 0),
 ('d77b0d99.jpg', 0),
 ('d049139f.jpg', 1),
 ('e0d17db9.jpg', 1),
 ('ca32b8c8.jpg', 0),
 ('ccc87a03.jpg', 0),
 ('d4d5efbe.jpg', 1),
 ('da258189.jpg', 0),
 ('edf66b63.jpg', 0),
 ('b90c1985.jpg', 0),
 ('bfaf7b24.jpg', 1),
 ('d41d2a8b.jpg', 1),
 ('d20acd55.jpg', 1),
 ('d2b0ed0f.jpg', 0),
 ('d0c3811c.jpg', 1),
 ('ed6097ae.jpg', 0),
 ('cca5ae46.jpg', 0),
 ('cfa90c60.jpg', 1),
 ('bc0e5b55.jpg', 0),
 ('e79dea50.jpg', 0),
 ('ed6248a0.jpg', 0),
 ('c2ee6643.jpg', 1),
 ('de2a2b5c.jpg', 1),
 ('c6047c76.jpg', 0),
 ('defe8dfd.jpg', 0),
 ('cbdf3524.jpg', 1),
 ('eda32fb6.jpg', 0),
 ('d92834e8.jpg', 1),
 ('d5766643.jpg', 1),
 ('c91f2dde.jpg', 0),
 ('c59e259c.jpg', 0),
 ('c8633b3b.jpg', 1),
 ('db935849.jpg', 1),
 ('c0691d58.jpg', 1),
 ('e03acd80.jpg', 1),
 ('c56de6f6.jpg', 0),
 ('e790c694.jpg', 1),
 ('ede3d40a.jpg', 0),
 ('de9788ab.jpg', 1),
 ('b55338e0.jpg', 1),
 ('d62ac512.jpg', 0),
 ('d31b429d.jpg', 0),
 ('e1122f3e.jpg', 1),
 ('c2269bf0.jpg', 0),
 ('cac72316.jpg', 1),
 ('d9e0accd.jpg', 1),
 ('ebbe548e.jpg', 0),
 ('b6eee896.jpg', 0),
 ('d9900014.jpg', 0),
 ('c3ebcae5.jpg', 0),
 ('ccc59b72.jpg', 1),
 ('c606c2f6.jpg', 0),
 ('ba962f6b.jpg', 0),
 ('dec0f1e2.jpg', 1),
 ('ed72fd6c.jpg', 1),
 ('d7678327.jpg', 0),
 ('e67c9fc4.jpg', 0),
 ('bc12540b.jpg', 1),
 ('c2827204.jpg', 0),
 ('e464e9f0.jpg', 1),
 ('d8f2f823.jpg', 0),
 ('d7f73903.jpg', 0),
 ('d4663719.jpg', 1),
 ('b6f685c7.jpg', 1),
 ('d6dd6ec9.jpg', 1),
 ('b6c39fe7.jpg', 1),
 ('c181d1ec.jpg', 0),
 ('ed3719a5.jpg', 1),
 ('ce937c2f.jpg', 0),
 ('c8658c7f.jpg', 0),
 ('eda99fd4.jpg', 0),
 ('e69c40e0.jpg', 0),
 ('e7fb7d17.jpg', 1),
 ('de5ae127.jpg', 1),
 ('dce07da8.jpg', 0),
 ('e082c75d.jpg', 0),
 ('cc7ab727.jpg', 1),
 ('d7564109.jpg', 0),
 ('d1777610.jpg', 0),
 ('b7a684e3.jpg', 0),
 ('dc1fad40.jpg', 0),
 ('cc8e914d.jpg', 0),
 ('d29a3551.jpg', 0),
 ('d933e0f5.jpg', 1),
 ('c2064729.jpg', 1),
 ('eb8d55bb.jpg', 0),
 ('e122901f.jpg', 1),
 ('d1f89f72.jpg', 1),
 ('db1587fb.jpg', 1),
 ('d011d8c4.jpg', 1),
 ('c367f6ff.jpg', 0),
 ('d3b5ea13.jpg', 0),
 ('e71090be.jpg', 1),
 ('d7ed4d8e.jpg', 0),
 ('db02e30d.jpg', 0),
 ('c642ef75.jpg', 0),
 ('d2c5df8a.jpg', 1),
 ('e0f8b602.jpg', 1),
 ('c833cd61.jpg', 0),
 ('d706d008.jpg', 0),
 ('e628fac1.jpg', 0),
 ('c7b64e77.jpg', 0),
 ('d5e7c454.jpg', 0),
 ('bbda60e4.jpg', 1),
 ('d3f19bd2.jpg', 1),
 ('e9d3a97d.jpg', 0),
 ('d5a75c58.jpg', 1),
 ('e056f1f9.jpg', 1),
 ('c8cbf440.jpg', 1),
 ('ccd2b014.jpg', 0),
 ('c7a6635a.jpg', 0),
 ('e7f13c3d.jpg', 1),
 ('b625bbf8.jpg', 1),
 ('ec174460.jpg', 0),
 ('ea0fca13.jpg', 0),
 ('ec908e75.jpg', 1),
 ('cae5ce56.jpg', 1),
 ('b965e3aa.jpg', 1),
 ('c64c2fc2.jpg', 1),
 ('c480551d.jpg', 1),
 ('c6d44ae2.jpg', 0),
 ('d4b83208.jpg', 1),
 ('befe8c5c.jpg', 0),
 ('cbe2448a.jpg', 1),
 ('bb9cc8c9.jpg', 0),
 ('e5b574e3.jpg', 1),
 ('e5bb9358.jpg', 1),
 ('ca4be818.jpg', 1),
 ('b76786bd.jpg', 0),
 ('be593352.jpg', 1),
 ('d19b4740.jpg', 1),
 ('beefc26e.jpg', 1),
 ('e23c247a.jpg', 1),
 ('c1bfc81f.jpg', 1),
 ('dd40c31b.jpg', 0),
 ('e471125e.jpg', 0),
 ('d1d12715.jpg', 1),
 ('d89f1b97.jpg', 1),
 ('b9a97231.jpg', 1),
 ('d24d8e4b.jpg', 0),
 ('ec0aba1e.jpg', 1),
 ('cba2af51.jpg', 0),
 ('bdf217f5.jpg', 1),
 ('c596c93c.jpg', 1),
 ('e8482e4d.jpg', 1),
 ('d33b6c1c.jpg', 1),
 ('d0176e1d.jpg', 0),
 ('d5098447.jpg', 0),
 ('b55400a2.jpg', 0),
 ('e798a501.jpg', 1),
 ('bd64800e.jpg', 0),
 ('e2607cb9.jpg', 1),
 ('cf035aba.jpg', 0),
 ('e3b43ab8.jpg', 0),
 ('c055fbb7.jpg', 0),
 ('d5461e01.jpg', 1),
 ('c25c7fbf.jpg', 0),
 ('cd6227a6.jpg', 1),
 ('ec200664.jpg', 0),
 ('e763db87.jpg', 0),
 ('dbcacd86.jpg', 1),
 ('d6c951a0.jpg', 0),
 ('d9bdf5a8.jpg', 0),
 ('c1e03c85.jpg', 0),
 ('e48208b3.jpg', 0),
 ('bc5aae3a.jpg', 1),
 ('cb0877d2.jpg', 0),
 ('b9db66f8.jpg', 0),
 ('b6399423.jpg', 0),
 ('dce236ac.jpg', 1),
 ('c4e0b2d3.jpg', 1),
 ('c83bf3b8.jpg', 1),
 ('d75fb466.jpg', 1),
 ('e0eb1696.jpg', 1),
 ('de97e1a9.jpg', 1),
 ('c099a9a0.jpg', 0),
 ('df8062b8.jpg', 0),
 ('b7aeafc6.jpg', 0),
 ('baf16c49.jpg', 0),
 ('b95f62ba.jpg', 1),
 ('bbda390f.jpg', 1),
 ('d587bf83.jpg', 1),
 ('fb6fe557.jpg', 0),
 ('ee75902b.jpg', 0),
 ('f374a94a.jpg', 0),
 ('f4c92a8d.jpg', 0),
 ('fd6a752a.jpg', 1),
 ('f5b0b1c2.jpg', 1),
 ('f89230f6.jpg', 1),
 ('fbb813d0.jpg', 1),
 ('ffd0a9aa.jpg', 1),

In [ ]:
submit = pd.read_csv("/content/drive/MyDrive/super-ai-engineer-season-6-individual-hackathon-house-recognition/sample_submission.csv")

In [ ]:
submit

            id  answer
0     e4b420b0     0.0
1     23efa479     0.0
2     1f0f2402     0.0
3     8a60480c     NaN
4     11f20127     NaN
...        ...     ...
1545  ed44ac4d     NaN
1546  a2067109     NaN
1547  1481178a     NaN
1548  340a3e9d     NaN
1549  af393f0c     NaN

[1550 rows x 2 columns]

In [ ]:
ss = pd.DataFrame(predictions)

In [ ]:
ss

                 0  1
0     5b22e513.jpg  1
1     7e78ba7d.jpg  1
2     7045ee0e.jpg  1
3     583e01c9.jpg  0
4     5bcca9b9.jpg  1
...            ... ..
1545  58d343f2.jpg  1
1546  6a5a68ee.jpg  0
1547  7ba6d581.jpg  0
1548  5d871084.jpg  0
1549  7d51a6fc.jpg  1

[1550 rows x 2 columns]

In [ ]:
ss = ss.rename(columns={0: "id", 1: "answer"})
ss["id"] = ss["id"].str.replace(".jpg", "")

In [ ]:
submit = submit.set_index("id")
ss = ss.set_index("id")
df_sorted = ss.reindex(submit.index)

In [ ]:
df_sorted

          answer
id
e4b420b0       0
23efa479       0
1f0f2402       0
8a60480c       0
11f20127       0
...          ...
ed44ac4d       1
a2067109       1
1481178a       1
340a3e9d       1
af393f0c       1

[1550 rows x 1 columns]

In [ ]:
df_sorted.to_csv("submit_house.csv")